### ISSUE TITLE
BUG Check for isDeleted property on ctx.query

### ISSUE THREAD

**Issue by israelglar** [GuruSolution/loopback-softdelete#1]
On the function logQuery in Model.observe('access'), to check if the query already has property isDeleted, the code shouldn't be  !ctx.query.isDeleted but !ctx.query.hasOwnProperty('isDeleted')

The code should look like this:

`if (!ctx.query.hasOwnProperty('isDeleted') && (!ctx.query.where || ctx.query.where && JSON.stringify(ctx.query.where).indexOf('isDeleted') == -1)) {
            if (!ctx.query.where) ctx.query.where = {};
            ctx.query.where.isDeleted = false;
        }`

That should be like this because the property isDeleted is a boolean, so checking for ctx.query.isDeleted will return false when the property is set to false already, and will create an unnecessary ctx.query.where.isDeleted that can create bugs

**Comment by juanvillegas** [comment]
See: https://github.com/smylen-inc/loopback-softdelete
